name: SFTP Upload (Overwrite Only)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  sftp-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload to SFTP
        uses: cross-the-world/sftp-pipeline@v1.1.0
        with:
          host: ${{ secrets.ser }}
          user: ${{ secrets.usr }}
          pass: ${{ secrets.psw }}
          port: 22
          local_dir: 'public_html' # Folder di repo GitHub Anda
          remote_dir: 'public_html' # Folder yang terlihat di gambar Anda
          args: '-o StrictHostKeyChecking=no'
