name: SFTP Upload (Overwrite Only)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  sftp-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload to SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          host: ${{ secrets.ser }}
          username: ${{ secrets.usr }}
          password: ${{ secrets.psw }}
          port: 22
          local_path: './public_html/' # Folder di GitHub (pastikan folder ini ada di repo)
          remote_path: 'public_html'    # Folder tujuan (sesuai gambar Anda)
          sftp_args: '-o StrictHostKeyChecking=no'
